### ISSUE TITLE
Nuxt.js example

### ISSUE THREAD

**Issue by wett1988** [JiriChara/vue-kindergarten#13]
Is it possible to add an example for Nuxt.js in repo?

Using the information from the [Readme](https://github.com/JiriChara/vue-kindergarten/blob/master/README.md), I was able to configure `Perimeter`, but do not understand how to configure `Sandbox` and `Governess` for Nuxt.js app

**Comment by JiriChara** [comment]
@wett1988 I will add an example of using vue-kindergarten this week. The problem with Nuxt.js is that the API is not yet stable enough and there might be some breaking changes coming.

Integration of kindergarten into Nuxt is pretty straightforward, but I am not sure what is the up-to-date way to protect routes in Nuxt. Maybe @pi0 can give us an advice?

**Comment by pi0** [comment]
Hey @wett1988 @JiriChara .
Actually I've never used kindergarten but it sounds already super awesome and useful +1. I suggest having something more than just a template but an official [Nuxt Module](https://github.com/nuxt/modules) for one-liner `nuxt` + `vue-kengergarten` integration!

**Comment by pi0** [comment]
The only concern that would be nuxt 1.0 release is Vue 2.3 SSR engine changes and plugins are no longer running in an isolated context. So it think we may need some additional steps for proper and safe integration. Anyway would be happy helping to integrate with modules.

**Comment by JiriChara** [comment]
@wett1988, @pi0,

Nuxt module would be awesome. I am super-busy until Wednesday, but I should have some time for the rest of the week to look into it!

**Comment by JiriChara** [comment]
Sorry for being so unresponsive on this issue, but I am waiting for the stable release on Nuxt and proper documentation on routing. I would like to come with the best practice for protecting routes in Nuxt.

**Comment by pi0** [comment]
Hi @JiriChara. NP. Nuxt is actually stable enough and will not have breaking changes until 1.0, we are just waiting for a while getting user feedbacks and making final minor fixes.

> and proper documentation on routing.

If there is not already an open issue, Would you please create a ticket on [nuxt/docs](https://github.com/nuxt/docs) explaining more about exactly which part you need? 

> best practice for protecting routes in Nuxt.

As a quick answer: I think [route middle](https://nuxtjs.org/guide/routing#middleware) would be the best option.

**Comment by JiriChara** [comment]
Hey @pi0,

Sorry my mistake. Just came back from holiday and last time I checked the documentation then it was for older version. Great job guys :tada:. I will have a look into it.

**Comment by JiriChara** [comment]
@wett1988 I have added an example of usage with Nuxt into README: https://github.com/JiriChara/vue-kindergarten#usage-with-nuxtjs
