### ISSUE TITLE
Rule names collision

### ISSUE THREAD

**Issue by vfailla** [JiriChara/vue-kindergarten#17]
Hello @JiriChara, first of all thank you for your work on kindergarten and vue-kindergarten.

I'm working right now on a Vuejs project where I have multiple perimeters, some of which have the same rule name (e.g. read()).
Everything works fine except when I use 2 or more perimeters into the same component.
The typical example could be a top menu, that needs to know whether to render a link based on user role.

In such a case, it seems that the $user.isAllowed('read') and $account.isAllowed('read') interfere each other, so that both return the same thing (please, see the code below).

The only workaround I found is to differentiate the names as "readUser" and "readAccount" (instead of just "read").
But this seems to be redundant, considering we already have the "purpose" that could work as a scope.

To give you a context, here follows a small piece of code:

    // topmenu.vue
    <template>
        <v-toolbar class="blue darken-4" light>
            <v-toolbar-items class="hidden-sm-and-down">
                <v-toolbar-item v-show="$user.isAllowed('read')" :router="true" :href="{ name: 'users.index' }" ripple>Users</v-toolbar-item>
                <v-toolbar-item v-show="$account.isAllowed('read')" :router="true" :href="{ name: 'accounts.index' }" ripple>Accounts</v-toolbar-item>
            </v-toolbar-items>
        </v-toolbar>
    </template>
    <script>
        export default {
            computed: {
                ...mapGetters('auth', ['isLoggedIn', 'profile']),
            },
          ...
            perimeters: [
                accountsPerimeter,
                usersPerimeter
            ]
        }
    </script>

    // BasePerimeter.js
    import { Perimeter } from 'vue-kindergarten'
    import store from 'vuex'
    import _ from 'lodash'

    export default class BasePerimeter extends Perimeter {
        isSuperAdmin() {
            const res = this.hasRole('super_admin');
            return res;
        }

        hasRole(roleName) {
            if (!this.child) {
            return false;
        }
            const res = _.includes(this.child.role_names, roleName);
            return res;
        }
    }

    // Account.js
    import BasePerimeter from './BasePerimeter';
    export default new BasePerimeter({
        purpose: 'account',
        can: {
            read() {
                const _isSuperAdmin = this.isSuperAdmin();
                return _isSuperAdmin;
            }
        },
    });

    // User.js
    import BasePerimeter from './BasePerimeter';
    export default new BasePerimeter({
        purpose: 'user',
        can: {
            read() {
                const _isSuperAdmin = this.isSuperAdmin();
                return !_isSuperAdmin;
            }
        },
    });

Another strange thing is that, looking at the console, $account and $user objects seem to be indefinitely nested each other, like this:

![user_account](https://user-images.githubusercontent.com/8330624/27872531-5f9589d8-61a9-11e7-8c46-b3aa469fe2c5.jpg)

Is there something I misunderstood?

Thank you in advance,
Enzo

**Comment by JiriChara** [comment]
Hey @vfailla,

Initially when I have developed kindergarten some years ago :-) - I wanted to make it very strict so whenever there are 2 perimeters in the sandbox that have rule with the same name, then the one which restricts user's access will always win. I agree that it doesn't really make sense when specifically calling `isAllowed` through the purpose. I am working on a fix.. For now as workaround you can create your perimeters and set governess explicitly:

```js
// Account.js
import { HeadGoverness } from 'vue-kindergarten';

import BasePerimeter from './BasePerimeter';

export default new BasePerimeter({
    purpose: 'account',

    can: {
        read() {
            const _isSuperAdmin = this.isSuperAdmin();
            return _isSuperAdmin;
        }
    },

    governess: HeadGoverness,
});


// User.js
import { HeadGoverness } from 'vue-kindergarten';

import BasePerimeter from './BasePerimeter';

export default new BasePerimeter({
    purpose: 'user',

    can: {
        read() {
            const _isSuperAdmin = this.isSuperAdmin();
            return !_isSuperAdmin;
        }
    },

    governess: HeadGoverness,
});
```

Thanks,

Jiri

**Comment by vfailla** [comment]
Thank you so much @JiriChara... the workaround you suggested works fine!

All the best,
Enzo

**Comment by JiriChara** [comment]
I am glad that it is working for you @vfailla! I have a fix that is working, but would like to test the hell out of it :-). You can follow the progress here: https://github.com/JiriChara/kindergarten/pull/18/files. New release should be ready by tomorrow, unless I will find another issues.

**Comment by vfailla** [comment]
Wonderful, I'll follow the progress... please, let me know whether I can help you with some tests.

Thank you again,
Enzo

**Comment by JiriChara** [comment]
@vfailla you can now upgrade to `0.3.0` :-)

**Comment by vfailla** [comment]
Hi @JiriChara, I've upgraded to `0.3.0`
I confirm it is working right now! 👍
I'll let you know in case I find something strange (I hope no  :-) ).

Thank you so much for taking care,
E.
