### ISSUE TITLE
Importing Perimeters Error

### ISSUE THREAD

**Issue by singiankay** [JiriChara/vue-kindergarten#29]
Not sure if I should post this here.
This is about the tutorial in the link [https://codeburst.io/role-based-authorization-for-your-vue-js-and-nuxt-js-applications-using-vue-kindergarten-fd483e013ec5](url)

If I added this code, `import * as perimeters from '../perimeters';`

Then an error is thrown.

probably es6 errors, or duplication of imports. I just don't know.

[HMR] bundle has 1 errors
client.js?7955:176 ./src/router/index.js
Module not found: Error: Can't resolve '../perimeters' in 'E:\kay\vue\vuecomplete\src\router'
 @ ./src/router/index.js 15:0-44
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

I made a stackoverflow post [https://stackoverflow.com/questions/47666323/why-cant-i-import-these-javascript-files?noredirect=1#comment82292155_47666323](url) about this

**Comment by singiankay** [comment]
Hi, I solved my question above by adding an index.js to the perimeters folder and importing the perimeters I made..

I'm still following the blog post, however, I had another error guarding the routes, here's my current config
```
router.beforeEach((to, from, next) => {
  const perimeter = perimeters[`${to.name}Perimeter`];
  if (perimeter) {
    const sandbox = createSandbox(child(store), {
      perimeters: [
        perimeter,
      ],
      governess: new RouteGoverness({ from, to, next }),
    });
    return sandbox.guard('route')
  }
  return next()
})
```
When I use this and then try to access any other pages, I get this error:

```
TypeError: Cannot read property 'from' of undefined
    at new RouteGoverness (RouteGoverness.js?4856:3)
    at eval (Sandbox.js?b6b0:129)
    at arrayEach (_arrayEach.js?b1cf:15)
    at forEach (forEach.js?0c52:38)
    at Sandbox.loadPerimeter (Sandbox.js?b6b0:113)
    at new Sandbox (Sandbox.js?b6b0:80)
    at createSandbox (createSandbox.js?9621:19)
    at eval (index.js?3672:76)
    at iterator (vue-router.esm.js?880d:1870)
    at step (vue-router.esm.js?880d:1652)
```

I'm not sure whether to use the blog post or the instructions here in github since the codes are somewhat different.

Also, I'm not sure about this code
```
Vue.use(VueKindergarten, {
	child: (store) => {
		return store.state.user
	}
})
```

but this code works for me,
```
Vue.use(VueKindergarten, {
	child,
})
```
When should I use these two? I am using vuex.

**Comment by JiriChara** [comment]
If you have following implementation of `RouteGoverness`:

```
export default class RouteGoverness extends HeadGoverness {
  constructor({ from, to, next }) {
    super();

    this.next = next;
    this.from = from;
    this.to = to;
  }

  guard(action) {
    this.next(super.isAllowed(action) ? undefined : '/');
  }
}
```

then you have to make sure to pass an object to the constructor, because:

```js
constructor({ from, to, next }) {
  // ...
}
```

is transpiled by babel to something like this

```js
constructor(obj) {
  var from = obj.from;
  var to = obj.to;
  var next = obj.next;
  // ...
}
```

it's called object destructuring. You can change the constructor function to:

```js
constructor({ from, to, next } = {}) {
  // ...
}
```

or just always make sur that you are passing an object to `RouteGoverness` when creating new instance. Let me know if you made it work.

**Comment by singiankay** [comment]
I'm still not able to do it.

I think what's happening is that the 'from' being passed in the router is a null value.

```
router.beforeEach((to, from, next) => {
  console.log(to)
  console.log(from)
  console.log(next)
  const perimeter = perimeters[`${to.name}Perimeter`];
  if (perimeter) {
    const sandbox = createSandbox(child(store), {
      perimeters: [
        perimeter,
      ],
      governess: new RouteGoverness({ from, to, next }),
    });
    return sandbox.guard('route')
  }
  return next()
})`
```

Here's the log:

**to**
{name: "hello", meta: {…}, path: "/hello", hash: "", query: {…}, …}

**from**
{name: null, meta: {…}, path: "/", hash: "", query: {…}, …}

**next**
 if (to === false || isError(to)) {
     // next(false) -> abort navigation, ensure current URL
     this$1.ensureURL(true);
     abort(to);
 } else if (
         …

**Comment by singiankay** [comment]
This code fixed the issue!
Thanks

```
constructor({ from, to, next } = {}) {
  // ...
}
```
