### ISSUE TITLE
Can I use it along with Firebase authentication ?

### ISSUE THREAD

**Issue by xerosanyam** [JiriChara/vue-kindergarten#3]

**Comment by JiriChara** [comment]
@xerosanyam you can use vue-kindergarten with any authentication provider. I recommend using `vuex` for state management and store the information about the current user and her permissions in the store and just point the `child` getter to it, but you can also have your own logic to retrieve the user's permissions. Vue-Kindergaten is targeting large applications, that have complicated authorization logic and where you want to move that logic from your components to perimeters.

**Comment by JiriChara** [comment]
@xerosanyam I am closing this issue. Feel free to open new ticket if you have some issues.
