### ISSUE TITLE
Guarding Routes

### ISSUE THREAD

**Issue by singiankay** [JiriChara/vue-kindergarten#30]
Hi, I managed to do the tutorial  [https://codeburst.io/role-based-authorization-for-your-vue-js-and-nuxt-js-applications-using-vue-kindergarten-fd483e013ec5](url)

But how do I use this format as stated in this repository?
```
router.beforeEach((to, from, next) => {
  to.matched.some((routeRecord) => {
    const perimeter = routeRecord.meta.perimeter
    const Governess = routeRecord.meta.governess || RouteGoverness
    const action = routeRecord.meta.perimeterAction || 'route'

    if (perimeter) {
      const sandbox = createSandbox(child(), {
        governess: new Governess(),
        perimeters: [
          perimeter,
        ],

      })

      return sandbox.guard(action, { to, from, next })
    }

    return next()
  })
})
```
Can you help me? I attached some parts of my config files

[attachment.zip](https://github.com/JiriChara/vue-kindergarten/files/1541973/attachment.zip)

**Comment by JiriChara** [comment]
Hi @singiankay,

sorry for late reply! I am not sure if I understand your problem :thinking: 

If you want to have some real-life example you might check this for example: https://github.com/JiriChara/jch-fe/blob/master/src/router/index.js
