### ISSUE TITLE
Guarding routes tree/hierarchy

### ISSUE THREAD

**Issue by jonagoldman** [JiriChara/vue-kindergarten#4]
In your [example](https://medium.com/@JiriChara/role-based-authorization-for-your-vue-js-and-nuxt-js-applications-using-vue-kindergarten-fd483e013ec5), you use ```to.name``` to create a single perimeter.

```js
router.beforeEach((to, from, next) => {
  const perimeter = perimeters[`${to.name}Perimeter`];
  if (perimeter) {
    const sandbox = createSandbox(child(store), {
      perimeters: [
        perimeter,
      ],
    });
    if (!sandbox.isAllowed('route')) {
      return next('/');
    }
  }
  return next();
});
```

But what if I have a routes tree where a parent route has a perimeter and a child route has another one? Or even multiple... I guess I need to look into the ```to.matched``` array... but can you give me an example on how to correctly deal with it? Thanks.

**Comment by Kinvaras** [comment]
Hi @jonagoldman,

I encountered the same problem 2 days ago and I probably found something interesting about it.
Actually, you were right, you need to look into the `to.matched` array. According to [this](https://router.vuejs.org/en/api/route-object.html), `to.matched` is an array containing all route records from parent to child.

I guess the right thing to do is creating a sandbox for every record. If a record is not allowed to be routed, you do your rejection logic and break the loop.

```javascript
router.beforeEach((to, from, next) => {
  for (let i = 0; i < to.matched.length; i++) {
    const routeRecord = to.matched[i];
    const perimeter = perimeters[`${routeRecord.name}Perimeter`];

    if (perimeter) {
      const sandbox = createSandbox(child(store), {
        perimeters: [
          perimeter
        ]
      });

      if (!sandbox.isAllowed('route')) {
        console.log('UNAUTHORIZED');
        // Your rejection logic here
      }
    }
  }

  return next();
});
```

We could probably optimize this.

**Comment by JiriChara** [comment]
Hey @jonagoldman, @Kinvaras,

Sorry for delayed reply - I was kind bit busy last couple of weeks.

There are many ways to guard your routes. I can think of following:

## 1) In component (use governess of the component)

Component:

``` vue
<template>
  <div>Hello</div>
</template>

<script>
  import myPerimeter from '@/perimeters/my';
  import RouteGoverness from '@/governesses/RouteGoverness';

  export default {
    perimeters: [
      myPerimeter,
    ],

    governess: new RouteGoverness(),

    beforeRouteEnter(to, from, next) {
      next((vm) => {
        vm.$guard('view', { to, from, next });
      });
    },
  };
</script>
```

Governess:

```js
import { HeadGoverness } from 'vue-kindergarten';

export default class RouteGoverness extends HeadGoverness {
  guard(action, { next }) {
    try {
      super.guard(action);
    } catch (e) {
      next('/');
    }

    next();
  }
}
```

The problem with this approach is that we can't access the instance of the component (`vm`) directly in the `beforeRouteEnter` (see. http://router.vuejs.org/en/advanced/navigation-guards.html#in-component-guards) so **Vue will actually start rendering your component and fetching data and then redirect**. Usually it's fast enough, but it might not be what you actually want.

## 2) In component (use sandbox helper)

Guard helper:

```js
import { createSandbox } from 'vue-kindergarten';

import child from '@/child';
import store from '@/store';
import RouteGoverness from '@/governesses/RouteGoverness';

const guard = (perimeter, action, { from, to, next }) => {
  const sandbox = createSandbox({
    child: child(store),

    perimeters: [
      perimeter,
    ],

    governess: new RouteGoverness({ from, to, next }),
  });

  return sandbox.guard(action);
};
```

Component:

```vue
<template>
  <div>Hello</div>
</template>

<script>
  import guardRoute from '@/utils/guardRoute';
  import myPerimeter from '@/perimeters/my';

  export default {
    perimeters: [
      myPerimeter,
    ],

    beforeRouteEnter(to, from, next) {
      return guardRoute(myPerimeter, 'view', { to, from, next });
    },
  };
</script>
```

## 3) Create route/perimeter map

You have to make sure that you are using named routes:

```js
export default new Router({
  routes: [
    {
      path: '/',
      name: 'home', // name is unique
      component: Home,
    },

    {
      path: '/secret',
      name: 'secret',
      component: Secret,

      children: [
        {
          path: 'subroute',
          name: 'supersecret',
          component: SuperSecret,
        },
      ],
    },
  ],
});
```

Create a map of perimeters and routes:

```js
import {
  homePerimeter,
  secretPerimeter,
} from 'perimeters';

export default {
  home: homePerimeter,
  secret: secretPerimeter,
  supersecret: secretPerimeter,
};
```

And the before each callback:

```js
import routePerimeterMap from '@/routePerimeterMap';

router.beforeEach((to, from, next) => {
  const perimeter = routePerimeterMap[to.name];

  if (perimeter) {
    const sandbox = createSandbox(child(store), {
      perimeters: [
        perimeter,
      ],
      governess: new RouteGoverness({ from, to, next }),
    });
    return sandbox.guard('route');
  }

  return next();
});
```

Vue-Router is very flexible and there are probably some other ways to achieve the same. If you guys have any idea how to make this process easier, then just let me know!

**Comment by JiriChara** [comment]
## 4) Add perimeter and governess to route meta

This is so far my favorite solution.

```js
const router = new Router({
  routes: [
    {
      path: '/',
      name: 'home',
      component: Home,
    },

    {
      path: '/users',
      name: 'user-list',
      component: UserList,
      meta: {
        perimeter: userPerimeter,
        perimeterAction: 'viewList',
      },
    },
  ],
});

router.beforeEach((to, from, next) => {
  to.matched.forEach((routeRecord) => {
    const perimeter = routeRecord.meta.perimeter;
    const Governess = routeRecord.meta.governess || RouteGoverness;
    const action = routeRecord.meta.perimeterAction || 'route';

    if (perimeter) {
      const sandbox = createSandbox(child(), {
        governess: new Governess({
          from,
          to,
          next,
        }),

        perimeters: [
          perimeter,
        ],
      });

      return sandbox.guard(action);
    }

    return next();
  });
});

export default router;

```

**Comment by jonagoldman** [comment]
Thanks!! I will try it in the next few days and let you know!

**Comment by JiriChara** [comment]
@jonagoldman closing this issue. Feel free to re-open if you still have issues

**Comment by ghost** [comment]
@JiriChara Hi, I am trying to implement an real life example using the 2nd method you provided above, by using the beforeRouteEnter hook in the component to handle access to the page but somehow I'm missing something...

This is what I have at the moment. I tried to integrate the method only for the Bye page. 
https://codesandbox.io/s/jlr64njl9w

I tried to replicate an example I saw on [codeburst](https://codeburst.io/role-based-authorization-for-your-vue-js-and-nuxt-js-applications-using-vue-kindergarten-fd483e013ec5) and update the code to use the newest approach but doesn't seem to work...

I tried to debug, and it looks like the HeadGoverness internally throws a 'Child is not allowed' error.. couldn't figure out what to do with that..

You have an idea why it's not working or how I could handle error while trying to access unauthorized pages?
Thanks for your time, also awesome concept!
