### ISSUE TITLE
govern vs can / cannot

### ISSUE THREAD

**Issue by richardwhatever** [JiriChara/vue-kindergarten#40]
Hi, 

What is the difference between the properties on the perimeter class 'govern' and 'can'. You seem to use them interchangeably in different documentation.

Example 'can'

```
createPerimeter({
  purpose: 'article',

  can: {
    read: () => true

    // only admin or moderator can update articles
    update(article) {
      return this.isAdmin() || (this.isCreator(article) && this.isModerator());
    },

    // if user can update articles then she can also destroy them
    destroy(article) {
      return this.isAllowed('update', article);
    }
  },
```

Example 'govern'

```
export default new BasePerimeter({
  purpose: 'bye',
  govern: {    
    'can route': () => true,
    'can viewParagraph': function () {
      return this.isAdmin();
    },
  },
});
```

Thanks,

**Comment by JiriChara** [comment]
Hey @richardwhatever,

they both are basically the same. Initially there was only `govern` object , but I found it little bit harder to write/read, so I added `can`.

Pick whatever you like more. I personally prefer `can`
