### ISSUE TITLE
simple issue npm install instead of npm add

### ISSUE THREAD

**Issue by cayaner** [JiriChara/vue-kindergarten#6]
simple issue npm install instead of npm add 
see:
![jirichara vue kindergarten modular security for vue vuex vue router and nuxt](https://cloud.githubusercontent.com/assets/19613212/26455894/f7ba2ae6-4117-11e7-8219-4ed243fadbcd.png)

**Comment by JiriChara** [comment]
Thanks @cayaner! Fixed
